### ISSUE TITLE
Setting yourself to ready will start the game too early

### ISSUE THREAD

**Issue by sylvanelite** [FalseProof/FEMultiplayer#4]
A number of issues:
- If there's only 1 player in the lobby, it'll start the game when they hit ready, but there will be no opponent
- If there's more than 1 player in the lobby, it will start the game regardless of teams. If both players ready on Blue team, it'll start with both on blue, causing bugs.
- Spectators count as players, even though they aren't on a team.

**Comment by sylvanelite** [comment]
Fix: Check that there's 2 players in the lobby, and that both are on different teams. Don't count spectators.

**Comment by FalseProof** [comment]
I know some commenters were curious if we could do a sim player, although that would be basically making an FE game. So I agree that we should patch out the ability to start a game without 2 players. I do know some people like to team build, so is there any way we could bring that code into the waiting lobby scene?
